import type { MotionPreset, MuscleGroup, ProductContentItem } from '../types'

export const motionPresetLabels: Record<MotionPreset, string> = { auto: 'Automático', squat: 'Agachamento', lunge: 'Afundo', pushup: 'Empurrar', row: 'Puxada / remada', deadlift: 'Levantamento', press: 'Desenvolvimento', plank: 'Prancha', strength: 'Força geral' }
export const muscleGroupLabels: Record<MuscleGroup, string> = { chest: 'Peitoral', back: 'Costas', shoulders: 'Ombros', arms: 'Braços', core: 'Core', glutes: 'Glúteos', quadriceps: 'Quadríceps', hamstrings: 'Posteriores', calves: 'Panturrilhas' }
export const defaultMuscles: Record<Exclude<MotionPreset, 'auto'>, MuscleGroup[]> = { squat: ['quadriceps', 'glutes', 'core'], lunge: ['quadriceps', 'glutes', 'hamstrings'], pushup: ['chest', 'shoulders', 'arms', 'core'], row: ['back', 'arms', 'core'], deadlift: ['hamstrings', 'glutes', 'back', 'core'], press: ['shoulders', 'arms', 'core'], plank: ['core', 'shoulders'], strength: ['core', 'arms'] }

export function inferMotionPreset(title: string): Exclude<MotionPreset, 'auto'> {
  const value = title.toLocaleLowerCase('pt-BR')
  if (/agach|squat/.test(value)) return 'squat'; if (/afundo|passada|lunge/.test(value)) return 'lunge'; if (/flex|supino|push|peito/.test(value)) return 'pushup'; if (/remada|puxada|row/.test(value)) return 'row'; if (/terra|deadlift|levantamento/.test(value)) return 'deadlift'; if (/desenvolvimento|shoulder|militar/.test(value)) return 'press'; if (/prancha|plank/.test(value)) return 'plank'; return 'strength'
}

export function BuiltInExerciseMotion({ item, compact = false }: { item: ProductContentItem; compact?: boolean }) {
  const selectedPreset = item.motion_preset && item.motion_preset !== 'auto' ? item.motion_preset : inferMotionPreset(item.title)
  const focused = item.muscle_focus?.length ? item.muscle_focus : defaultMuscles[selectedPreset]
  const isActive = (muscle: MuscleGroup) => focused.includes(muscle) ? 'active' : ''
  const activated = focused.map((muscle) => muscleGroupLabels[muscle]).join(' · ')
  return <div className={`motion-frame embedded-motion preset-${selectedPreset} ${compact ? 'compact' : ''}`} role="img" aria-label={`${item.title}. Ativação: ${activated}`}><svg viewBox="0 0 240 190" aria-hidden="true"><g className="motion-grid"><path d="M20 158 H220" /><path d="M35 35 V158 M205 35 V158" /></g><g className="mesh-silhouette"><circle cx="120" cy="27" r="14" /><path d="M120 42 C104 46 97 68 101 87 L108 104 L93 148 M120 42 C136 46 143 68 139 87 L132 104 L147 148 M101 61 L61 94 L77 133 M139 61 L179 94 L163 133" /></g><g className="muscle-layer"><ellipse className={`muscle muscle-chest ${isActive('chest')}`} cx="120" cy="61" rx="24" ry="13" /><ellipse className={`muscle muscle-back ${isActive('back')}`} cx="120" cy="67" rx="25" ry="18" /><ellipse className={`muscle muscle-shoulders ${isActive('shoulders')}`} cx="96" cy="55" rx="9" ry="14" /><ellipse className={`muscle muscle-shoulders ${isActive('shoulders')}`} cx="144" cy="55" rx="9" ry="14" /><ellipse className={`muscle muscle-arms ${isActive('arms')}`} cx="68" cy="91" rx="8" ry="19" transform="rotate(-28 68 91)" /><ellipse className={`muscle muscle-arms ${isActive('arms')}`} cx="172" cy="91" rx="8" ry="19" transform="rotate(28 172 91)" /><ellipse className={`muscle muscle-core ${isActive('core')}`} cx="120" cy="80" rx="12" ry="22" /><ellipse className={`muscle muscle-glutes ${isActive('glutes')}`} cx="110" cy="103" rx="12" ry="10" /><ellipse className={`muscle muscle-glutes ${isActive('glutes')}`} cx="130" cy="103" rx="12" ry="10" /><ellipse className={`muscle muscle-quadriceps ${isActive('quadriceps')}`} cx="105" cy="123" rx="10" ry="20" transform="rotate(7 105 123)" /><ellipse className={`muscle muscle-quadriceps ${isActive('quadriceps')}`} cx="135" cy="123" rx="10" ry="20" transform="rotate(-7 135 123)" /><ellipse className={`muscle muscle-hamstrings ${isActive('hamstrings')}`} cx="106" cy="128" rx="8" ry="19" /><ellipse className={`muscle muscle-hamstrings ${isActive('hamstrings')}`} cx="134" cy="128" rx="8" ry="19" /><ellipse className={`muscle muscle-calves ${isActive('calves')}`} cx="101" cy="151" rx="7" ry="14" /><ellipse className={`muscle muscle-calves ${isActive('calves')}`} cx="139" cy="151" rx="7" ry="14" /></g></svg><div className="motion-caption"><strong>{motionPresetLabels[selectedPreset]}</strong><span>Ativação: {activated}</span></div></div>
}
